name: 'Deployed Commit Writer Action'
description: 'Automatically create a file containing the currently deployed commit'
inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
  DESTINATION_FILE_PATH:
    description: "Name of the file containing metadata of commit"
    required: false
    default: "COMMIT_INFO"
  COMMIT_MESSAGE:
    description: "Commit message"
    required: true
  COMMITTER:
    description: "Commit user"
    required: true
  BASE:
    required: false
    description: "The base reference to be used for the affected evaluation."
  HEAD:
    required: false
    description: "'The head reference to be used for the affected evaluation.'"
runs:
  using: "node16"
  main: "dist/index.js"